# Generated by Django 4.2.9 on 2024-02-05 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=255)),
                ('recipient_name', models.CharField(max_length=255)),
                ('sending_point', models.CharField(max_length=255)),
                ('receiving_point', models.CharField(max_length=255)),
                ('sending_index', models.IntegerField()),
                ('receiving_index', models.IntegerField()),
                ('letter_type', models.IntegerField(choices=[(1, 'Письмо'), (2, 'Заказное письмо'), (3, 'Ценное письмо'), (4, 'Экспресс-письмо')])),
                ('weight', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=255)),
                ('recipient_name', models.CharField(max_length=255)),
                ('sending_point', models.CharField(max_length=255)),
                ('receiving_point', models.CharField(max_length=255)),
                ('sending_index', models.IntegerField()),
                ('receiving_index', models.IntegerField()),
                ('notification_phone', models.CharField(max_length=20)),
                ('parcel_type', models.IntegerField(choices=[(1, 'Мелкий пакет'), (2, 'Посылка'), (3, 'Посылка 1 класса'), (4, 'Ценная посылка'), (5, 'Посылка международная'), (6, 'Экспресс-посылка')])),
                ('payment_amount', models.IntegerField()),
            ],
        ),
    ]
